---
title: "03_Reweighter.Output.Summaries"
format: html
editor: visual
---
# 0.0 Environment Set Up
# 0.1 Filepath Set Up
```{r}
#===============================================================================
#TODO: 
# 1. Create a way to loop through scenarios and headship rates based on a list

#===============================================================================
### Set Scenario Names ###
#Population Scenario
scen <- 'Scenario_1'
#Headship rate Scenario
hdshp <- 'acs1721'

#Use when Rproject is open
#root <- '../../../../Data/Working/Regional_Control_Totals/'

# Base root. Toggle between S: and K: drive depedning on mapped paths on your computer
base <- "K:/DataServices/Projects/Current_Projects/"
#base <- "S:/Network Shares/K Drive/DataServices/Projects/Current_Projects/"

# General K drive filepath
root <- paste0(base, "Housing/StatewideHousingPlan/04_Analysis/Data/Working/Regional_Control_Totals/")

# Set output filepath
output_path <- paste0(base, "Housing/StatewideHousingPlan/04_Analysis/Data/Working/Regional_Control_Totals/", scen, "/")

# Reweighter files path
rwt_path <- paste0(base, "Housing/StatewideHousingPlan/04_Analysis/Data/Working/Reweighter/", scen, "/Output_Files/")

# Set knitr path
knitr::opts_knit$set(root.dir = root)
```

# 0.2 Set Package Dependencies + Set Environment Variables, Set up data keys
```{r}
library(tidycensus)
library(tidyverse)
library(data.table)
library(reticulate)
library(mapcdatakeys)
library(janitor)
library(readxl)

##get rid of scientific notation
options(scipen = 999)
#Set random seed
set.seed(351)

#Set up muni data keys
#MPO Data Keys
keys.mpo <- mapcdatakeys::all_muni_data_keys |> 
  select(
    muni_id, muni_name, mpo
  ) |> 
  mutate(
    muni_id = as.character(muni_id),
    muni_name = ifelse(muni_name == "Manchester-by-the-Sea", "Manchester", muni_name)
  )

#RPA Data Keys
keys.rpa <- mapcdatakeys::all_muni_data_keys |> 
  select(
    muni_id, muni_name, rpa_acr
  ) |> 
  mutate(
    muni_id = as.character(muni_id),
    muni_name = ifelse(muni_name == "Manchester-by-the-Sea", "Manchester", muni_name)
  )
```

# 1.0 Load Reweighter Output Data
```{r}
# Set a column of years corresponding to the projection years considered
years <- c(2020,2030,2035,2040,2045,2050)

# Create null objects for each scenario's full reweighted PUMS dataset. 
# One will be used per script run depending on the value given to "scen" at the outset of the script.
s1.df <- NULL

s2.sf <- NULL

s3.sf <- NULL

s4.df <- NULL

# Standardized function for reading reweighted PUMS data for each scenario and projection year.
read_rwt.files <- function(scenario, year){
  read.csv(
      paste0(rwt_path, "reweighted_PUMS_",scen,"_MAPC101_",i,".csv")
    )
}

# Loads in reweighted PUMS data for each year and scenario.
# Compiles data into a single dataframe which is generated earlier.
for (i in years) {
  for (j in scen){
    
    if (scen == "Scenario_1"){
    
      tmp <- read_rwt.files(scenario = scen, year = i) |> mutate(year = i)
    
      s1.df <- bind_rows(s1.df, tmp)
    
      rm(tmp)
    
      print(paste0("Finished Reading and Appending Scenario: ", scen, " for Year: ", i))
  
  }
    else if (scen == "Scenario_2"){
    
      tmp <- read_rwt.files(scenario = scen, year = i) |> mutate(year = i)
    
      s2.df <- bind_rows(s2.df, tmp)
    
      rm(tmp)
    
      print(paste0("Finished Reading and Appending Scenario: ", scen, " for Year: ", i))
    
  }
    else if (scen == "Scenario_3"){
    
      tmp <- read_rwt.files(scenario = scen, year = i) |> mutate(year = i)
    
      s3.df <- bind_rows(s3.df, tmp)
    
      rm(tmp)
    
      print(paste0("Finished Reading and Appending Scenario: ", scen, " for Year: ", i))
    
  }
   else{
    
      tmp <- read_rwt.files(scenario = scen, year = i) |> mutate(year = i)
    
      s4.df <- bind_rows(s4.df, tmp)
    
      rm(tmp)
    
      print(paste0("Finished Reading and Appending Scenario: ", scen, " for Year: ", i))
    
  }
 }
}

```
